[package]
name = "bdecode"
version = "0.1.0"
authors = ["Árni Dagur <arni@dagur.eu>"]
edition = "2018"

[[bench]]
name = "bdecode"
path = "benchmarks/bdecode.rs"
harness = false

[dependencies]
memchr = "*"

[dev-dependencies]
criterion = "0.3"
url = "2"